version: 0.2

phases:
  install:
    commands:
      - echo "Installing Packer..."
      - curl -o packer.zip https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
      - unzip packer.zip
      - rm -f packer.zip
      - chmod +x packer
      - sudo mv packer /usr/local/bin

  build:
    commands:
      - echo "Building Windows Packer AMI..."
      - packer build packer-windows-ami.json
artifacts:
  files:
    - '**/*'
