version: 0.2

phases:
  install:
    commands:
      - echo "Installing git..."
      - apt-get update
      - apt-get install -y git
      - echo "Installing Packer..."
      - curl -o packer.zip https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
      - unzip packer.zip
      - sudo mv packer /usr/local/bin/
  pre_build:
    commands:
      - echo "Configuring Git credentials..."
      - git config --global user.email "manjun566@gmail.com"
      - git config --global user.name "ManjunathanRajan"
      - echo "Fetching latest GitHub release tag..."
      - git fetch --tags
      - git checkout main
      - git pull origin main
      - export CURRENT_RELEASE_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
      - echo $CURRENT_RELEASE_TAG
      - export NEW_RELEASE_TAG=v$(echo $CURRENT_RELEASE_TAG | cut -c2- | awk -F. '{$NF+=1;}1' | sed 's/ /./g')
      - echo $NEW_RELEASE_TAG
      - echo "Creating and pushing new release tag: ${NEW_RELEASE_TAG} on the main branch"
      - git tag -a ${NEW_RELEASE_TAG} -m "Release ${NEW_RELEASE_TAG}"
      - git push origin ${NEW_RELEASE_TAG}
      - export GITHUB_RELEASE_TAG=${NEW_RELEASE_TAG}
  build:
    commands:
      - echo "Validating Packer template..."
      - packer validate packer.json
      - echo "Building golden image..."
      - packer build -var "github_release_tag=${GITHUB_RELEASE_TAG}" packer.json
