version: 0.2

env:
  variables:
    ECR_REPOSITORY_URI: "716514200744.dkr.ecr.us-west-2.amazonaws.com/my-ecr-repo"

phases:
  pre_build:
    commands:
      - echo "Building Docker image with Packer and AWS CLI"
      - docker build -t packer-aws .
  build:
    commands:
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - docker tag packer-aws:latest $ECR_REPOSITORY_URI:packer-aws
      - echo "Building AMI using Packer"
      - packer build packer.json
  post_build:
    commands:
      - echo "Pushing Docker image to ECR"
      - docker push $ECR_REPOSITORY_URI:packer-aws
