version: 0.2

phases:
  install:
    commands:
      - echo "Installing git..."
      - yum update -y
      - yum install -y git
      - echo "Installing Packer..."
      - curl -o packer.zip https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
      - unzip packer.zip
      - sudo mv packer /usr/local/bin/
      - echo "Installing GitHub credential managers..."
      - curl -sL https://github.com/microsoft/Git-Credential-Manager/releases/latest/download/gcm-core-linux_amd64.deb -o gcmcore.deb
      - sudo dpkg -i gcmcore.deb
  pre_build:
    commands:
      - echo "Configuring Git credentials..."
      - git config --global credential.credentialStore cache
      - git config --global credential.helper 'cache --timeout=1200'
      - git config --global user.email "manjun566@gmail.com"
      - git config --global user.name "ManjunathanRajan"
      - GCM_PATH=$(which git-credential-manager)
      - echo "Git Credential Manager installed at $GCM_PATH"
      - git config --global credential.helper "$GCM_PATH"
      - git remote set-url origin https://github.com/ManjunathanRajan/GI_AWS.git
      - echo "Fetching latest GitHub release tag..."
      - git fetch --tags
      - git checkout main
      - git pull origin main
      - export CURRENT_RELEASE_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
      - echo $CURRENT_RELEASE_TAG
      - export NEW_RELEASE_TAG=$(echo "v$(echo $CURRENT_RELEASE_TAG | cut -c2- | awk -F. '{$NF+=1;}1' OFS='.')")
      - echo $NEW_RELEASE_TAG
      - git tag -a ${NEW_RELEASE_TAG} -m "Release ${NEW_RELEASE_TAG}"
      - chmod +x git_retry_push.sh
      - ./git_retry_push.sh "git push origin ${NEW_RELEASE_TAG}"
      - export GITHUB_RELEASE_TAG=${NEW_RELEASE_TAG}
  build:
    commands:
      - echo "Validating Packer template..."
      - packer validate packer.json
      - echo "Building golden image..."
      - packer build -var "github_release_tag=${GITHUB_RELEASE_TAG}" packer.json
  post_build:
    commands:
      - echo "Tagging GitHub release..."
      - export RELEASE_VERSION=$(git describe --tags --abbrev=0)
      - export NEW_RELEASE_VERSION="v$(echo $RELEASE_VERSION | cut -c2- | awk -F. '{$NF+=1;}1' | sed 's/ /./g')"
      - git tag -a ${NEW_RELEASE_VERSION} -m "Release ${NEW_RELEASE_VERSION}"
      - ./git_retry_push.sh "git push origin ${NEW_RELEASE_VERSION}"
