version: 0.2

phases:
  install:
    commands:
      - echo "Installing Packer..."
      - curl -o packer.zip https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
      - unzip packer.zip
      - rm -f packer.zip
      - chmod +x packer
      - sudo mv packer /usr/local/bin
  pre_build:
    commands:
      - echo "Installing GnuPG and jq..."
      - yum update -y && yum install -y gnupg jq
      - echo "Retrieving GPG private key from Secrets Manager..."
      - export GPG_PRIVATE_KEY=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-west-2:716514200744:secret:github-gpg-nOvMMy --query SecretString --output text | jq -r '.gpg_private_key')
      - echo "Importing GPG private key into GPG..."
      - echo "$GPG_PRIVATE_KEY" | gpg --import
      - echo "Configuring Git for GPG key signing..."
      - git config --global user.signingkey "283626CEE37D5FC2"
      - git config --global user.email "manjun566@gmail.com"
  build:
    commands:
      - echo "Building Windows Packer AMI..."
      - packer validate packer-windows-ami.json
      - packer build packer-windows-ami.json
  post_build:
    commands:
    - echo "Creating a signed tag at the commit for the release..."
    - git checkout main
    - git pull origin main
    - NEW_TAG="GA-01"
    - TAG_MESSAGE="Release $NEW_TAG"
    - git tag -s $NEW_TAG -m "$TAG_MESSAGE"
    - echo "Pushing the signed tag to the remote repository..."
    - git push origin $NEW_TAG
artifacts:
  files:
    - '**/*'
