version: 0.2

phases:
  install:
    commands:
      - echo "Installing Packer..."
      - curl -o packer.zip https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
      - unzip packer.zip
      - rm -f packer.zip
      - chmod +x packer
      - sudo mv packer /usr/local/bin
  pre_build:
    commands:
      - echo "Setting up Git credentials for GitHub authentication..."
      - yum update -y && yum install -y jq
      - export GITHUB_USERNAME=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-west-2:716514200744:secret:gh-usr-pwd-eRsTUm --query SecretString --output text | jq -r '.username')
      - export GITHUB_PASSWORD=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-west-2:716514200744:secret:gh-usr-pwd-eRsTUm --query SecretString --output text | jq -r '.password')
      - git config --global credential.helper 'cache --timeout=3600'
      - echo "Cloning the repository using Git credentials..."
      - echo "protocol=https
            host=github.com
            username=$GITHUB_USERNAME
            password=$GITHUB_PASSWORD" | git credential-cache store
      - git clone https://github.com/ManjunathanRajan/golden-image-windows.git
      - echo "Changing the working directory to the cloned repository..."
      - cd golden-image-windows
      - echo "Setting Git user name and email for this repository..."
      - git config user.email "manjun566@gmail.com"
      - git config user.name "ManjunathanRajan"
      - echo "Fetching the latest commit from the os-release branch..."
      - git fetch origin OS-Release
      - git checkout FETCH_HEAD
      - echo "Creating a signed tag at the commit for the release..."
      - NEW_TAG="GA-01"
      - TAG_MESSAGE="Release $NEW_TAG"
      - git tag -s $NEW_TAG -m "$TAG_MESSAGE"
      - echo "Pushing the signed tag to the original GitHub repository..."
      - git push origin $NEW_TAG
  build:
    commands:
      - echo "Building Windows Packer AMI..."
      - packer validate packer-windows-ami.json
      - packer build packer-windows-ami.json
artifacts:
  files:
    - '**/*'
