version: 0.2

env:
  variables:
    ECR_REPOSITORY_URI: "716514200744.dkr.ecr.us-west-2.amazonaws.com/my-ecr-repo"
  secrets-manager:
    AWS_ACCESS_KEY_ID: aws_secrets:AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: aws_secrets:AWS_SECRET_ACCESS_KEY

phases:
  pre_build:
    commands:
      - echo "Building Docker image with Packer and AWS CLI"
      - docker build -t packer-aws .
  build:
    commands:
      - echo "Logging in to Amazon ECR"
      - export AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY
      - LOGIN_COMMAND=$(aws ecr get-login --no-include-email --region $AWS_REGION)
      - eval $LOGIN_COMMAND
      - docker tag packer-aws:latest $ECR_REPOSITORY_URI:packer-aws
      - echo "Building AMI using Packer"
      - packer build packer.json
  post_build:
    commands:
      - echo "Pushing Docker image to ECR"
      - docker push $ECR_REPOSITORY_URI:packer-aws

artifacts:
  files:
    - manifest.json
