version: 0.2

phases:
  install:
    commands:
      - echo "Installing Packer..."
      - curl -o packer.zip https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
      - unzip packer.zip
      - rm -f packer.zip
      - chmod +x packer
      - sudo mv packer /usr/local/bin
      - echo "Setting up SSH key for GitHub authentication..."
      - echo "$SSH_PRIVATE_KEY" > private_key.pem
      - chmod 600 private_key.pem
      - eval $(ssh-agent -s)
      - ssh-add private_key.pem
      - echo "Cloning the repository using SSH..."
      - git clone git@github.com:your-username/your-repo.git
      - echo "Changing the working directory to the cloned repository..."
      - cd your-repo
      - echo "Setting Git user name and email for this repository..."
      - git config user.email "you@example.com"
      - git config user.name "Your Name"
      - echo "Fetching the latest commit from the os-release branch..."
      - git fetch origin os-release
      - git checkout FETCH_HEAD
  build:
    commands:
      - echo "Building Windows Packer AMI..."
      - packer validate packer-windows-ami.json
      - packer build packer-windows-ami.json
  post_build:
    commands:
      - echo "Switching to the main branch..."
      - git checkout main
      - echo "Creating a new tag and release with a descriptive title based on the os-release branch and pushing it to the main branch..."
      - NEW_TAG="GA-01"
      - TAG_TITLE="Golden Image Windows 2019-$NEW_TAG"
      - git tag -a $NEW_TAG -m "$TAG_TITLE"
      - git push origin $NEW_TAG
      - echo "Creating a new release with the same title..."
      - RELEASE_TITLE="$TAG_TITLE"
      - git release create -t "$RELEASE_TITLE" -n "$RELEASE_TITLE" $NEW_TAG
artifacts:
  files:
    - '**/*'
