version: 0.2

phases:
  install:
    commands:
      - echo "Installing Packer..."
      - curl -o packer.zip https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
      - unzip packer.zip
      - rm -f packer.zip
      - chmod +x packer
      - sudo mv packer /usr/local/bin

  pre_build:
    commands:
      - echo "Making mount_chroot.sh executable..."
      - chmod +x mount_chroot.sh
  build:
    commands:
      - echo "Building Packer AMI..."
      - packer build packer-linux-ami.json
artifacts:
  files:
    - '**/*'
