version: 0.2

phases:
  install:
    commands:
      - echo "Installing Packer..."
      - curl -o packer.zip https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip
      - unzip packer.zip
      - rm -f packer.zip
      - chmod +x packer
      - sudo mv packer /usr/local/bin
  pre_build:
    commands:
      - echo "Setting up Git authentication using PAT..."
      - yum update -y && yum install -y python
      - SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-west-2:716514200744:secret:pat_gh-b7FRfI --query SecretString --output json)
      - GITHUB_PAT=$(echo $SECRET_VALUE | python -c "import sys, json; print(json.loads(json.load(sys.stdin))['PAT'])")
      - echo "Setting environment variable for Git authentication..."
      - export GIT_ASKPASS=$(pwd)/git-askpass.sh
      - echo -e '#!/bin/sh\necho $GITHUB_PAT' > $GIT_ASKPASS
      - chmod +x $GIT_ASKPASS
      - echo "Cloning the repository using PAT..."
      - git clone https://github.com/ManjunathanRajan/golden-image-windows.git
      - echo "Changing the working directory to the cloned repository..."
      - cd golden-image-windows
      - echo "Setting Git user name and email for this repository..."
      - git config user.email "manjun566@gmail.com"
      - git config user.name "ManjunathanRajan"
      - echo "Pulling the latest changes from the main branch..."
      - git checkout main
      - git pull origin main
      - echo "Creating a tag at the latest commit..."
      - NEW_TAG="GA-01"
      - TAG_MESSAGE="Release $NEW_TAG"
      - git tag $NEW_TAG -m "$TAG_MESSAGE"
      - echo "Pushing the tag to the original GitHub repository..."
      - git push origin $NEW_TAG
  build:
    commands:
      - echo "Building Windows Packer AMI..."
      - packer validate packer-windows-ami.json
      - packer build packer-windows-ami.json
artifacts:
  files:
    - '**/*'
