name: Build Linux AMI with Packer

on:
  workflow_dispatch: {}

env:
  AWS_REGION: us-west-2
  PRODUCT_VERSION: "1.8.6"

jobs:
  build-linux-ami:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
    - name: Install jq
      run: sudo apt-get install jq

    - name: Set up Packer
      uses: hashicorp/setup-packer@v2.0.0
      id: setup
      with:
        version: ${{ env.PRODUCT_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
        role-session-name: GitHub-Action-Role
        aws-region: ${{ env.AWS_REGION }}

    - name: Validate Packer configuration
      run: packer validate packer-linux-ami.json

    - name: Build Windows AMI
      run: packer build packer-linux-ami.json
