name: Build Linux AMI with Packer

on:
  workflow_dispatch: {}

env:
  AWS_REGION: us-west-2
  PRODUCT_VERSION: "1.8.6"

jobs:
  build-linux-ami:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
    - name: Install jq
      run: sudo yum install -y jq

    - name: Set up Packer
      uses: hashicorp/setup-packer@v2.0.0
      id: setup
      with:
        version: ${{ env.PRODUCT_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
        role-session-name: GitHub-Action-Role
        aws-region: ${{ env.AWS_REGION }}

    - name: Ensure packer-amazon-chroot directory exists
      run: |
        sudo mkdir -p /tmp/packer-chroot
        sudo chown -R $(whoami):$(whoami) /tmp/packer-chroot
        ls -ld /tmp/packer-chroot

    - name: Create packer-chroot(/var/lock/) directory and set permissions
      run: |
        sudo mkdir -p /var/lock/packer-chroot
        sudo chown -R $(whoami):$(whoami) /var/lock/packer-chroot

    - name: Validate and Build Linux AMI
      run: |
        packer validate packer-linux-ami.json
        packer build packer-linux-ami.json
